name = "DirectRegistry"
uuid = "22c22277-0986-4687-925d-fd389cbfda78"
repo = "https://github.com/sefffal/DirectRegistry.git"
description = ""

[packages]
d0ffc639-4e6f-47d5-8eab-0368fa958583 = { name = "DirectImages", path = "D/DirectImages" }
